// ============================================================
// Self-Improvement Engine — Autonomous Meta-Learning Loop
//
// PURPOSE: LFI evaluates its own capabilities, identifies weaknesses,
// generates targeted training, re-trains, and measures improvement.
// This is the escape velocity mechanism — once this loop works,
// LFI can compound its intelligence without human intervention.
//
// ARCHITECTURE (inspired by: OODA loop + Schmidhuber's Gödel Machine
// + AlphaZero self-play + Friston's active inference):
//
//   OBSERVE:  Measure current capability across all domains
//   ORIENT:   Identify weakest areas and highest-impact improvements
//   DECIDE:   Generate a targeted improvement plan
//   ACT:      Execute the plan (train, practice, generate code, test)
//   REFLECT:  Compare before/after metrics. Did we improve?
//   RECURSE:  Feed the reflection into the next cycle
//
// SELF-PLAY TRAINING:
//   For coding: LFI generates a solution, evaluates it, learns from
//   errors, generates a better solution, evaluates again. The evaluation
//   function IS the teacher — no external LLM needed for this loop.
//
// META-COGNITION:
//   LFI tracks not just WHAT it knows, but HOW FAST it's learning,
//   WHERE it's plateauing, and WHAT strategies work best for which
//   domains. This meta-knowledge guides the improvement plan.
//
// STRATEGIC PLANNING:
//   The improvement engine doesn't just grind — it plans. It identifies
//   prerequisite skills, builds dependency graphs, and sequences
//   learning to maximize compound gains. Learning math helps coding.
//   Learning logic helps security. Learning coding helps everything.
// ============================================================

use crate::hdc::error::HdcError;
use crate::cognition::knowledge::KnowledgeEngine;
use crate::intelligence::code_eval::{CodeEvaluator, ChallengeLibrary, StaticAnalyzer, CodeIssue};
use crate::intelligence::training_data::{TrainingDataGenerator, TrainingAugmenter, AdversarialExamples};
use crate::intelligence::local_inference::{InferenceTrainer, InferenceTrainingConfig, InferenceBackend};
use crate::intelligence::benchmark::IntelligenceBenchmark;
use std::collections::HashMap;

// ============================================================
// Capability Profile — snapshot of current intelligence
// ============================================================

/// A snapshot of LFI's capabilities at a point in time.
#[derive(Debug, Clone)]
pub struct CapabilityProfile {
    /// Overall intelligence score (0.0 to 1.0).
    pub overall_score: f64,
    /// Per-domain mastery scores.
    pub domain_scores: HashMap<String, f64>,
    /// Coding evaluation score.
    pub coding_score: f64,
    /// Math reasoning score.
    pub math_score: f64,
    /// Security knowledge score.
    pub security_score: f64,
    /// Number of concepts known.
    pub concepts_known: usize,
    /// Timestamp of this profile.
    pub timestamp_ms: u64,
    /// Learning velocity: improvement rate per cycle.
    pub learning_velocity: f64,
}

impl CapabilityProfile {
    fn now() -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64
    }
}

// ============================================================
// Improvement Plan — what to do next
// ============================================================

/// A targeted improvement plan generated by the meta-learning engine.
#[derive(Debug, Clone)]
pub struct ImprovementPlan {
    /// What domains to focus on (ordered by priority).
    pub focus_domains: Vec<String>,
    /// Specific actions to take.
    pub actions: Vec<ImprovementAction>,
    /// Expected score improvement.
    pub expected_gain: f64,
    /// Rationale for this plan.
    pub rationale: String,
}

/// A specific improvement action.
#[derive(Debug, Clone)]
pub enum ImprovementAction {
    /// Train on examples in a specific domain.
    TrainDomain { domain: String, example_count: usize },
    /// Practice coding challenges at a specific difficulty.
    PracticeCoding { difficulty: f64, challenge_count: usize },
    /// Review and reinforce weak concepts.
    ReviewWeak { concepts: Vec<String> },
    /// Attempt harder challenges in an area of strength.
    PushBoundary { domain: String, target_difficulty: f64 },
    /// Cross-train: use strength in one domain to boost another.
    CrossTrain { source_domain: String, target_domain: String },
    /// Run adversarial examples to test robustness.
    AdversarialTest { domain: String },
}

// ============================================================
// Learning Curve Tracker
// ============================================================

/// Tracks learning velocity and plateau detection.
pub struct LearningCurve {
    /// History of scores over time: (timestamp_ms, score).
    history: Vec<(u64, f64)>,
    /// Per-domain learning curves.
    domain_curves: HashMap<String, Vec<(u64, f64)>>,
}

impl LearningCurve {
    pub fn new() -> Self {
        Self {
            history: Vec::new(),
            domain_curves: HashMap::new(),
        }
    }

    /// Record a score measurement.
    pub fn record(&mut self, score: f64) {
        let ts = CapabilityProfile::now();
        self.history.push((ts, score));
    }

    /// Record a domain-specific score.
    pub fn record_domain(&mut self, domain: &str, score: f64) {
        let ts = CapabilityProfile::now();
        self.domain_curves.entry(domain.to_string())
            .or_default()
            .push((ts, score));
    }

    /// Compute learning velocity (score improvement per measurement).
    /// Positive = improving. Zero = plateaued. Negative = regressing.
    pub fn velocity(&self) -> f64 {
        if self.history.len() < 2 { return 0.0; }
        let recent = &self.history[self.history.len().saturating_sub(5)..];
        if recent.len() < 2 { return 0.0; }
        let first = recent[0].1;
        let last = recent[recent.len() - 1].1;
        (last - first) / recent.len() as f64
    }

    /// Detect if learning has plateaued (velocity near zero for N measurements).
    /// BUG ASSUMPTION: plateau threshold is hardcoded. May need tuning.
    pub fn is_plateaued(&self) -> bool {
        self.velocity().abs() < 0.005 && self.history.len() > 5
    }

    /// Domain-specific velocity.
    pub fn domain_velocity(&self, domain: &str) -> f64 {
        let curve = match self.domain_curves.get(domain) {
            Some(c) if c.len() >= 2 => c,
            _ => return 0.0,
        };
        let recent = &curve[curve.len().saturating_sub(5)..];
        if recent.len() < 2 { return 0.0; }
        let first = recent[0].1;
        let last = recent[recent.len() - 1].1;
        (last - first) / recent.len() as f64
    }

    /// Domains that are plateauing (ordered by staleness).
    pub fn plateaued_domains(&self) -> Vec<String> {
        self.domain_curves.keys()
            .filter(|d| self.domain_velocity(d).abs() < 0.005)
            .cloned()
            .collect()
    }

    /// Total measurements recorded.
    pub fn measurement_count(&self) -> usize {
        self.history.len()
    }
}

// ============================================================
// Self-Improvement Engine — the core loop
// ============================================================

/// The autonomous self-improvement engine.
///
/// This is the meta-learning system. It:
/// 1. Profiles current capabilities
/// 2. Generates an improvement plan
/// 3. Executes the plan
/// 4. Measures the result
/// 5. Recurses
pub struct SelfImprovementEngine {
    /// Learning curve tracker.
    pub curve: LearningCurve,
    /// History of capability profiles.
    pub profile_history: Vec<CapabilityProfile>,
    /// Current improvement cycle number.
    pub cycle: usize,
    /// Code evaluator for coding challenges.
    pub code_evaluator: CodeEvaluator,
    /// Number of improvement cycles completed.
    pub total_cycles: usize,
}

impl SelfImprovementEngine {
    pub fn new() -> Self {
        debuglog!("SelfImprovementEngine::new: Initializing autonomous meta-learning");
        Self {
            curve: LearningCurve::new(),
            profile_history: Vec::new(),
            cycle: 0,
            code_evaluator: CodeEvaluator::new(),
            total_cycles: 0,
        }
    }

    /// STEP 1: Profile current capabilities.
    ///
    /// Measures LFI's knowledge across all domains and returns
    /// a comprehensive capability snapshot.
    pub fn profile(&self, knowledge: &KnowledgeEngine) -> CapabilityProfile {
        debuglog!("SelfImprovementEngine::profile: Measuring current capabilities");

        let domains = TrainingDataGenerator::domains();
        let mut domain_scores = HashMap::new();
        let mut total_score: f64 = 0.0;

        for domain in &domains {
            let mastery = knowledge.domain_mastery(domain);
            domain_scores.insert(domain.clone(), mastery);
            total_score += mastery;
        }

        let domain_count = domains.len().max(1);
        let overall = total_score / domain_count as f64;

        // Compute category scores
        let math_domains = ["math", "math_advanced", "logic", "reasoning"];
        let security_domains = ["security", "crypto", "psa", "networking", "social_eng",
                                "threat_intel", "ethical_hacking", "forensics"];
        let coding_domains = ["code", "devops", "systems_design"];

        let math_score = math_domains.iter()
            .filter_map(|d| domain_scores.get(*d))
            .copied()
            .sum::<f64>() / math_domains.len() as f64;

        let security_score = security_domains.iter()
            .filter_map(|d| domain_scores.get(*d))
            .copied()
            .sum::<f64>() / security_domains.len() as f64;

        let coding_score = coding_domains.iter()
            .filter_map(|d| domain_scores.get(*d))
            .copied()
            .sum::<f64>() / coding_domains.len() as f64;

        CapabilityProfile {
            overall_score: overall,
            domain_scores,
            coding_score,
            math_score,
            security_score,
            concepts_known: knowledge.concept_count(),
            timestamp_ms: CapabilityProfile::now(),
            learning_velocity: self.curve.velocity(),
        }
    }

    /// STEP 2: Generate an improvement plan based on current profile.
    ///
    /// Uses the Pareto principle: focus on the weakest domains first,
    /// because that's where the biggest gains are. But also consider
    /// prerequisite chains and cross-domain transfer.
    pub fn plan(&self, profile: &CapabilityProfile) -> ImprovementPlan {
        debuglog!("SelfImprovementEngine::plan: Generating improvement strategy");

        let mut actions = Vec::new();
        let mut focus_domains = Vec::new();

        // Sort domains by mastery (lowest first).
        let mut sorted_domains: Vec<(String, f64)> = profile.domain_scores.iter()
            .map(|(k, v)| (k.clone(), *v))
            .collect();
        sorted_domains.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));

        // Focus on weakest 5 domains.
        for (domain, mastery) in sorted_domains.iter().take(5) {
            focus_domains.push(domain.clone());

            if *mastery < 0.3 {
                // Very weak: basic training needed.
                actions.push(ImprovementAction::TrainDomain {
                    domain: domain.clone(),
                    example_count: 20,
                });
            } else if *mastery < 0.6 {
                // Moderate: push harder.
                actions.push(ImprovementAction::PushBoundary {
                    domain: domain.clone(),
                    target_difficulty: mastery + 0.2,
                });
            } else {
                // Strong: adversarial testing.
                actions.push(ImprovementAction::AdversarialTest {
                    domain: domain.clone(),
                });
            }
        }

        // Always include coding practice.
        let coding_difficulty = profile.coding_score.clamp(0.1, 0.9);
        actions.push(ImprovementAction::PracticeCoding {
            difficulty: coding_difficulty,
            challenge_count: 5,
        });

        // Cross-training: use strongest domain to boost weakest related domain.
        if let (Some(strongest), Some(weakest)) = (
            sorted_domains.last(),
            sorted_domains.first(),
        ) {
            if strongest.1 > 0.5 && weakest.1 < 0.3 {
                actions.push(ImprovementAction::CrossTrain {
                    source_domain: strongest.0.clone(),
                    target_domain: weakest.0.clone(),
                });
            }
        }

        // If plateaued: shake things up with adversarial examples.
        if self.curve.is_plateaued() {
            actions.push(ImprovementAction::AdversarialTest {
                domain: "all".into(),
            });
        }

        let expected_gain = if profile.overall_score < 0.3 {
            0.15 // Big gains early
        } else if profile.overall_score < 0.7 {
            0.08 // Moderate gains
        } else {
            0.03 // Diminishing returns
        };

        let rationale = format!(
            "Cycle {}: Overall {:.1}% (math={:.1}%, security={:.1}%, code={:.1}%). \
            Velocity={:.4}. Focus: {}. {}",
            self.cycle,
            profile.overall_score * 100.0,
            profile.math_score * 100.0,
            profile.security_score * 100.0,
            profile.coding_score * 100.0,
            profile.learning_velocity,
            focus_domains.join(", "),
            if self.curve.is_plateaued() { "PLATEAU DETECTED — injecting adversarial." } else { "" },
        );

        ImprovementPlan {
            focus_domains,
            actions,
            expected_gain,
            rationale,
        }
    }

    /// STEP 3: Execute an improvement plan.
    ///
    /// Returns the number of training actions completed.
    pub fn execute(
        &mut self,
        plan: &ImprovementPlan,
        knowledge: &mut KnowledgeEngine,
    ) -> Result<usize, HdcError> {
        debuglog!("SelfImprovementEngine::execute: {} actions in plan", plan.actions.len());
        let mut completed = 0;

        for action in &plan.actions {
            match action {
                ImprovementAction::TrainDomain { domain, example_count } => {
                    let examples = TrainingDataGenerator::domain_examples(domain);
                    let count = examples.len().min(*example_count);
                    if count > 0 {
                        let config = InferenceTrainingConfig::default();
                        let mut trainer = InferenceTrainer::new(config);
                        let _ = trainer.train_all(&examples[..count], knowledge);
                        completed += 1;
                    }
                }
                ImprovementAction::PracticeCoding { difficulty, challenge_count } => {
                    let challenges = ChallengeLibrary::all();
                    let relevant: Vec<_> = challenges.iter()
                        .filter(|c| (c.difficulty - difficulty).abs() < 0.3)
                        .take(*challenge_count)
                        .collect();
                    for challenge in relevant {
                        // Evaluate reference solution (self-play: learn from correct code).
                        let _ = self.code_evaluator.evaluate(challenge, &challenge.reference_solution);
                        // Learn the coding pattern.
                        let concept = format!("code_pattern_{}", challenge.id);
                        let _ = knowledge.learn_with_definition(
                            &concept,
                            &format!("Coding: {} — {}", challenge.description, challenge.signature),
                            &challenge.tags.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
                            *difficulty,
                            true,
                        );
                    }
                    completed += 1;
                }
                ImprovementAction::ReviewWeak { concepts } => {
                    for concept_name in concepts {
                        knowledge.reinforce(concept_name);
                    }
                    completed += 1;
                }
                ImprovementAction::PushBoundary { domain, target_difficulty } => {
                    let hard_examples = TrainingDataGenerator::domain_examples(domain)
                        .into_iter()
                        .filter(|e| e.difficulty >= *target_difficulty)
                        .collect::<Vec<_>>();
                    if !hard_examples.is_empty() {
                        let config = InferenceTrainingConfig::default();
                        let mut trainer = InferenceTrainer::new(config);
                        let _ = trainer.train_all(&hard_examples, knowledge);
                    }
                    completed += 1;
                }
                ImprovementAction::CrossTrain { source_domain, target_domain } => {
                    let _ = TrainingDataGenerator::apply_transfer(
                        knowledge, source_domain, 0.2,
                    );
                    debuglog!("CrossTrain: {} → {}", source_domain, target_domain);
                    completed += 1;
                }
                ImprovementAction::AdversarialTest { domain } => {
                    let adversarial = if domain == "all" {
                        AdversarialExamples::all()
                    } else {
                        AdversarialExamples::all().into_iter()
                            .filter(|e| e.domain == *domain)
                            .collect()
                    };
                    if !adversarial.is_empty() {
                        let config = InferenceTrainingConfig::default();
                        let mut trainer = InferenceTrainer::new(config);
                        let _ = trainer.train_all(&adversarial, knowledge);
                    }
                    completed += 1;
                }
            }
        }

        Ok(completed)
    }

    /// STEP 4: Reflect — measure improvement and update learning curve.
    pub fn reflect(
        &mut self,
        knowledge: &KnowledgeEngine,
    ) -> CapabilityProfile {
        let profile = self.profile(knowledge);

        self.curve.record(profile.overall_score);
        for (domain, score) in &profile.domain_scores {
            self.curve.record_domain(domain, *score);
        }

        self.profile_history.push(profile.clone());
        profile
    }

    /// RUN ONE FULL IMPROVEMENT CYCLE: profile → plan → execute → reflect.
    ///
    /// Returns (before_profile, after_profile, plan).
    pub fn run_cycle(
        &mut self,
        knowledge: &mut KnowledgeEngine,
    ) -> Result<(CapabilityProfile, CapabilityProfile, ImprovementPlan), HdcError> {
        self.cycle += 1;
        debuglog!("SelfImprovementEngine::run_cycle: CYCLE {}", self.cycle);

        // Before
        let before = self.profile(knowledge);

        // Plan
        let plan = self.plan(&before);
        debuglog!("SelfImprovementEngine: Plan rationale: {}", plan.rationale);

        // Execute
        let completed = self.execute(&plan, knowledge)?;
        debuglog!("SelfImprovementEngine: Executed {}/{} actions", completed, plan.actions.len());

        // Reflect
        let after = self.reflect(knowledge);

        let delta = after.overall_score - before.overall_score;
        debuglog!("SelfImprovementEngine: CYCLE {} complete. Score: {:.4} → {:.4} (delta={:+.4})",
            self.cycle, before.overall_score, after.overall_score, delta);

        self.total_cycles += 1;

        Ok((before, after, plan))
    }

    /// Run N improvement cycles autonomously.
    pub fn run_n_cycles(
        &mut self,
        n: usize,
        knowledge: &mut KnowledgeEngine,
    ) -> Result<Vec<CapabilityProfile>, HdcError> {
        debuglog!("SelfImprovementEngine::run_n_cycles: Running {} cycles", n);
        let mut profiles = Vec::new();

        for _ in 0..n {
            let (_, after, _) = self.run_cycle(knowledge)?;
            profiles.push(after);
        }

        Ok(profiles)
    }

    /// Generate a human-readable progress report.
    pub fn progress_report(&self) -> String {
        let mut report = String::new();
        report.push_str(&format!("=== Self-Improvement Report (Cycle {}) ===\n", self.cycle));

        if let Some(latest) = self.profile_history.last() {
            report.push_str(&format!("Overall:  {:.1}%\n", latest.overall_score * 100.0));
            report.push_str(&format!("Math:     {:.1}%\n", latest.math_score * 100.0));
            report.push_str(&format!("Security: {:.1}%\n", latest.security_score * 100.0));
            report.push_str(&format!("Coding:   {:.1}%\n", latest.coding_score * 100.0));
            report.push_str(&format!("Concepts: {}\n", latest.concepts_known));
            report.push_str(&format!("Velocity: {:+.4}\n", latest.learning_velocity));
        }

        if self.profile_history.len() >= 2 {
            let first = &self.profile_history[0];
            let last = self.profile_history.last().unwrap();
            let total_gain = last.overall_score - first.overall_score;
            report.push_str(&format!("Total improvement: {:+.1}% over {} cycles\n",
                total_gain * 100.0, self.cycle));
        }

        if self.curve.is_plateaued() {
            report.push_str("WARNING: Learning has plateaued. Adversarial injection recommended.\n");
        }

        report
    }
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_profile_empty_knowledge() {
        let engine = SelfImprovementEngine::new();
        let knowledge = KnowledgeEngine::new();
        let profile = engine.profile(&knowledge);

        // KnowledgeEngine seeds 36 concepts, some with domain overlap.
        assert!(profile.overall_score >= 0.0);
        assert!(profile.concepts_known > 0);
    }

    #[test]
    fn test_plan_focuses_on_weak_domains() {
        let engine = SelfImprovementEngine::new();
        let knowledge = KnowledgeEngine::new();
        let profile = engine.profile(&knowledge);
        let plan = engine.plan(&profile);

        assert!(!plan.focus_domains.is_empty(), "Plan should have focus domains");
        assert!(!plan.actions.is_empty(), "Plan should have actions");
        assert!(plan.expected_gain > 0.0, "Plan should expect some gain");
    }

    #[test]
    fn test_run_single_cycle() -> Result<(), HdcError> {
        let mut engine = SelfImprovementEngine::new();
        let mut knowledge = KnowledgeEngine::new();

        let (before, after, plan) = engine.run_cycle(&mut knowledge)?;

        assert!(!plan.actions.is_empty());
        assert!(after.concepts_known >= before.concepts_known,
            "Should learn new concepts: {} → {}", before.concepts_known, after.concepts_known);
        assert_eq!(engine.total_cycles, 1);
        Ok(())
    }

    #[test]
    fn test_run_multiple_cycles_improve() -> Result<(), HdcError> {
        let mut engine = SelfImprovementEngine::new();
        let mut knowledge = KnowledgeEngine::new();

        let profiles = engine.run_n_cycles(3, &mut knowledge)?;

        assert_eq!(profiles.len(), 3);
        // After 3 cycles, should have more concepts than at start.
        let initial_concepts = KnowledgeEngine::new().concept_count();
        let final_concepts = profiles.last().map(|p| p.concepts_known).unwrap_or(0);
        assert!(final_concepts > initial_concepts,
            "Should learn: {} → {}", initial_concepts, final_concepts);
        Ok(())
    }

    #[test]
    fn test_learning_curve_tracking() {
        let mut curve = LearningCurve::new();
        curve.record(0.1);
        curve.record(0.2);
        curve.record(0.3);
        curve.record(0.4);

        assert!(curve.velocity() > 0.0, "Improving curve should have positive velocity");
        assert!(!curve.is_plateaued(), "Improving curve should not be plateaued");
    }

    #[test]
    fn test_plateau_detection() {
        let mut curve = LearningCurve::new();
        // Flat scores → plateau
        for _ in 0..10 {
            curve.record(0.5);
        }

        assert!(curve.is_plateaued(), "Flat scores should detect plateau");
    }

    #[test]
    fn test_progress_report() -> Result<(), HdcError> {
        let mut engine = SelfImprovementEngine::new();
        let mut knowledge = KnowledgeEngine::new();

        let _ = engine.run_cycle(&mut knowledge)?;
        let report = engine.progress_report();

        assert!(report.contains("Self-Improvement Report"));
        assert!(report.contains("Overall:"));
        assert!(report.contains("Math:"));
        assert!(report.contains("Security:"));
        Ok(())
    }

    #[test]
    fn test_improvement_actions_cover_domains() {
        let engine = SelfImprovementEngine::new();
        let knowledge = KnowledgeEngine::new();
        let profile = engine.profile(&knowledge);
        let plan = engine.plan(&profile);

        // Should always include coding practice
        let has_coding = plan.actions.iter().any(|a|
            matches!(a, ImprovementAction::PracticeCoding { .. }));
        assert!(has_coding, "Plan should always include coding practice");
    }

    #[test]
    fn test_cross_training_strategy() {
        let engine = SelfImprovementEngine::new();
        let knowledge = KnowledgeEngine::new();
        let profile = engine.profile(&knowledge);
        let plan = engine.plan(&profile);

        // With fresh knowledge engine, there should be weak domains
        assert!(plan.actions.iter().any(|a|
            matches!(a, ImprovementAction::TrainDomain { .. })),
            "Fresh engine should have TrainDomain actions");
    }

    #[test]
    fn test_domain_velocity_tracking() {
        let mut curve = LearningCurve::new();
        curve.record_domain("math", 0.1);
        curve.record_domain("math", 0.3);
        curve.record_domain("math", 0.5);

        curve.record_domain("security", 0.4);
        curve.record_domain("security", 0.4);
        curve.record_domain("security", 0.4);

        assert!(curve.domain_velocity("math") > 0.0, "Math should be improving");
        assert!(curve.domain_velocity("security").abs() < 0.01, "Security should be flat");

        let plateaued = curve.plateaued_domains();
        assert!(plateaued.contains(&"security".to_string()),
            "Security should be identified as plateaued");
    }
}
